name: SonarCloud

on:
  workflow_dispatch:  # permite ejecuci√≥n manual
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    uses: zenwk-org/zenwk-infra/.github/workflows/sonarcloud.yml@main
    with:
      projectKey: ZenWkZen_zenwk-verification
      organization: zenwk
    secrets: inherit