name: SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:   #Habilita ejecuci√≥n manual desde Actions

jobs:
  sonar:
    uses: zenwk-org/infra-zenwk/.github/workflows/sonarcloud.yml@main
    with:
      working-directory: ./zenwk-verification
    secrets: inherit